CREATE TABLE IF NOT EXISTS hamburguesa(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    precio integer NOT  NULL,
    descripcion text,
    imagen text NOT NULL
);

CREATE TABLE IF NOT EXISTS ingrediente(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    descripcion text

);

CREATE TABLE hamburguesa_ingrediente (
  hamburguesa_id    int REFERENCES hamburguesa (id) ON UPDATE CASCADE ON DELETE CASCADE
, ingrediente_id int REFERENCES ingrediente (id) ON UPDATE CASCADE
, CONSTRAINT hamburguesa_ingrediente_pkey PRIMARY KEY (hamburguesa_id, ingrediente_id)  -- explicit pk
);

-- Insertar hamburguesa
INSERT INTO hamburguesa(nombre, precio, descripcion, imagen)
    VALUES('Big Mac', 5000, 'Hamburguesa del Mc', 'foto_big_mac');

INSERT INTO hamburguesa(nombre, precio, descripcion, imagen)
    VALUES('Juicy Lucy', 9000, 'Hamburguesa de la burguesia', 'foto_juicy_lucy');

INSERT INTO hamburguesa(nombre, precio, descripcion, imagen)
    VALUES('Whooper', 6000, 'Hamburguesa del Burger', 'foto_whooper');

-- Insertar ingredientes
INSERT INTO ingrediente(nombre, descripcion)
VALUES('Queso', 'Queso mantecoso');

INSERT INTO ingrediente(nombre, descripcion)
VALUES('Tomate', 'Tomate de la IV Region');

INSERT INTO ingrediente(nombre, descripcion)
VALUES('Palta', 'Palta Hass');